### ISSUE TITLE
RunnerMonitorLambda Nodejs 14x to Nodejs 18x

### ISSUE THREAD

**Issue by danjaran** [aws-samples/amazon-ec2-gitlab-runner#14]
Hi,

Seems the Depecration Phase 1 of Nodejs 14x and Nodejs 16x will be done shortly
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

is there any date when will be the  RunnerMonitoringLambda using Nodejs18, since the Nodejs18 need to adjust structure code.
```
  RunnerMonitorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-runner-monitor
      Description: "Monitors the state of the gitlab runners to trigger autoscaling events"
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Sub "${AWS::StackName}/${AWS::StackName}-runner-monitor-${TimeStamp}.zip"
      Handler: index.handler
      Role: !GetAtt RunnerMonitorRole.Arn
      Runtime: nodejs14.x
      Timeout: 900
      MemorySize: 256
      ReservedConcurrentExecutions: 1
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt RunnerMonitorSecurityGroup.GroupId
        SubnetIds: !Ref SubnetIds
      Environment:
        Variables:
          AUTOSCALING_GROUP_NAME: !Ref RunnerAutoScalingGroup
          MAXIMUM_CONCURRENT_JOBS_PER_RUNNER: !Ref Concurrent
          COUNT_OF_NEW_JOBS_BEFORE_SCALING: !Ref CountOfNewJobsBeforeScaling
          RUNNER_METRIC_NAMESPACE: !Sub "${AWS::StackName}-runner-metrics"
          RUNNER_JOB_COUNT_METRIC_NAME: !Sub "${AWS::StackName}-job-count"
          RUNNER_TARGET_CAPACITY_METRIC_NAME: !Sub "${AWS::StackName}-target-capacity"
          RUNNER_ACTUAL_CAPACITY_METRIC_NAME: !Sub "${AWS::StackName}-actual-capacity"
      Tags:
        - Key: "APP_ID"
          Value: !Ref AppId
        - Key: "COST_CENTER"
          Value: !Ref CostCenter
```

Thank you
